export interface Permission {
  id: number;
  name: string;
  description: string;
}

export enum PermissionEnum {
  ADD_USER = 1,
  GET_USERS = 2,
  EDIT_USER = 3,
  DELETE_USER = 4,

  ADD_TRUCK = 5,
  GET_TRUCKS = 6,
  EDIT_TRUCK = 7,
  DELETE_TRUCK = 8,

  ADD_DEVICE = 9,
  GET_DEVICES = 10,
  EDIT_DEVICE = 11,
  DELETE_DEVICE = 12,
  ACTIVATE_DEVICE = 13,
  CREATE_ALLOCATION = 14,
  RETURN_TRUCK = 15,
  UPDATE_USER_LOCATION = 16,
  UPDATE_USER_STATUS = 17,
  GET_COMPANY = 18,
  UPDATE_COMPANY = 19,
  GET_EQUIPMENTS = 20,
  GET_VEHICLE_BODIES = 21,
  GET_TOW_REASONS = 22,
  GET_VEHICLE_COLORS = 23,
  GET_STATES = 24,
  ADD_TOW = 25,
  CHANGE_TRUCK = 26,
  GET_NOTIFICATIONS = 27,
  UPDATE_FCM_TOKEN = 28,
  MARK_NOTIFICATIONS_READ = 29,
  UPDATE_TOW_STATUS = 30,

  UPLOAD_ATTACHMENT = 31,
  GET_TOWS = 32,
  GET_LOGS = 33,
  DOWNLOAD_ATTACHMENT = 34,
  EDIT_TOW = 35,
  ADD_TOW_DOCUMENT = 36,
  ADD_VEHICLE_PHOTO = 37,
  UPDATE_USER = 38,
  RESET_USER_PWD = 39,
  MARK_NOTIFICATIONS_UNREAD = 40,
  CREATE_ADDRESS_BOOK = 41,
  DELETE_ADDRESS_BOOK = 42,
  UPDATE_ADDRESS_BOOK = 43,
  RETRIEVE_ADDRESS_BOOK = 44,
  GET_ALLOCATION = 45,
}
